### PR TITLE
Update bower.json

### PR DESCRIPTION
**Pull request by pbechu**
Fix typo in bower.json that breaks the build

### CODE REVIEW

**Comment by sturdynut** [comment]
Eek!  Thank you for catching that one and fixing it. : )

**Comment by pbechu** [comment]
You're welcome. However i'm using a direct reference to an older commit
because I couldn't make the bower.json working :/ I will retry it on Monday
;)
Le 13 mars 2015 22:15, "Matti Salokangas" <notifications@github.com> a
écrit :

**Comment by sturdynut** [comment]
Cool, let me know if you run into any issues!

**Comment by pbechu** [comment]
Seems good for me! FYI you need to add git tags to your repo if you want to use semver (source: http://bower.io/docs/creating-packages/#register)

**Pull request merged**
