### PR TITLE
Fixed issue that phone-format-global.js did not create PhoneFormat object

### PR DESCRIPTION
**Pull request by andidev**
phone-format-global.js is no longer working after my last commits. This PR will fix the issues.

### CODE REVIEW

**Comment by sturdynut** [comment]
Thank you sir!

**Comment by andidev** [comment]
No problem!
Note that you also need to create a git tag for this new version 1.0.1, so that it will be available through bower. You can do so with:
```bash
git tag 1.0.1
```
and then push it to github with
```bash
git push origin 1.0.1
```

**Comment by sturdynut** [comment]
Done. :)

**Comment by andidev** [comment]
Thanks!

**Comment by andidev** [comment]
It seems as you forgot to pull the changes before creating the tag. So the tagged version in actually the same version as 1.0.0.

You need to remove the local and remote 1.0.1 tag, pull the latest changes t local local repo and then recreate and push the 1.0.1 tag again. Here's a cheatsheet
```bash
git tag 1.0.1
git push --delete origin 1.0.1
git pull
git tag 1.0.1
git push origin 1.0.1
```

Thanks in advance!

**Pull request merged**
